.\" Manpage for generateur-de-photos-identite.
.\" Contact karlito@martobre.fr to correct errors or typos.
.TH man 1 "03 Mar 2013" "1.0" "generateur-de-photos-identite man page"
.SH NAME
generateur-de-photos-identite \- A identity picture generator
.SH SYNOPSIS
generateur-de-photos-identite
.SH DESCRIPTION
generateur-de-photos-identite is a program designed to create home made identity pictures.
.SH OPTIONS
The generateur-de-photos-identite does not take any options.
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
Clement Roblot (karlito@martobre.fr)
